# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interintrnsip_2018',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.BigIntegerField()),
                ('CurrentCity', models.CharField(max_length=50)),
                ('Question1', models.TextField(verbose_name='Q1. Why should you be hired for this internship?')),
                ('Question2', models.TextField(verbose_name='Q2. Are you available for 1 month, starting immediately, for a full time internship at Delhi? If not, what is the time period you are available for and the earliest date you can start this internship on?')),
                ('Institute', models.CharField(blank=True, default='', max_length=150)),
                ('Degree', models.CharField(blank=True, default='', max_length=50)),
                ('Stream', models.CharField(blank=True, default='', max_length=100)),
                ('Choosed_Department', models.CharField(max_length=50)),
                ('Current_Year_Of_Graduation', models.CharField(max_length=50, null=True, verbose_name='Current Year Of Graduation')),
                ('Performance_PG', models.CharField(default='', max_length=50, verbose_name='PG Performance')),
                ('Performance_UG', models.CharField(blank=True, default='', max_length=50, verbose_name='UG Performance')),
                ('Performance_12', models.CharField(blank=True, default='', max_length=50, verbose_name='12 Performance')),
                ('Performance_10', models.CharField(blank=True, default='', max_length=50, verbose_name='10 Performance')),
                ('Link_to_application', models.URLField(verbose_name='Link to application')),
                ('Assigned_Department', models.CharField(choices=[('Data Analytics', 'Data Analytics'), ('Policy Research', 'Policy Research'), ('Social Media', 'Social Media'), ('Legal', 'Legal'), ('Human Resource', 'HumanResource')], default=' ', max_length=2, verbose_name='Assigned Department')),
                ('Status', models.CharField(choices=[('Select', 'Select'), ('NotSelect', 'Not Select'), ('Hold', 'Hold')], default=' ', max_length=2)),
                ('Assigned_Username', models.CharField(max_length=50)),
                ('Assigned_Password', models.CharField(max_length=50)),
            ],
        ),
    ]
