# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_auto_20180618_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.BigIntegerField()),
                ('Department', models.CharField(max_length=50)),
                ('Post', models.CharField(max_length=200)),
                ('Feedback', models.TextField()),
                ('Others', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='interintrnsip_2018',
            name='Assigned_Department',
            field=models.CharField(choices=[('Data Analytics', 'Data Analytics'), ('Policy Research', 'Policy Research'), ('Social Media', 'Social Media'), ('Legal', 'Legal'), ('Human Resource', 'HumanResource'), (' ', '---')], default=' ', max_length=2, verbose_name='Assigned Department'),
        ),
        migrations.AlterField(
            model_name='interintrnsip_2018',
            name='Status',
            field=models.CharField(choices=[('Select', 'Select'), ('NotSelect', 'Not Select'), ('Hold', 'Hold'), (' ', '---')], default=' ', max_length=2),
        ),
    ]
